all:
  hosts:
    openshift_namespace_test:
      ansible_connection: local
      ansible_host: localhost
      ansible_python_interpreter: "{{ ansible_playbook_python }}"
      openshift_namespace: svc0041t-wordpress
  vars:
    # Routing
    www_host: wpn-test.epfl.ch
    avi_route_access_level: public
    # Storage
    pv_name: pv-svc0041-www-auxiliary-test-app
    pv_storage: 1Gi
    # NGINX
    nginx_real_ip_header: X-Forwarded-For
